# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'pcso-dev'

# variables:
#   buildConfiguration: 'dev'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
# steps:
# - task: DotNetCoreCLI@2


variables:
  buildConfiguration: 'Release'
  # The path to the project file from the sample repo
  projectPath: 'pipelines-dotnet-core.csproj'

- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      name: 'pcso-dev'
    steps:
    # This line downloads the code so the build task can find it
    - checkout: self

    - task: DotNetCoreCLI@2
      displayName: 'Build Project'
      inputs:
        command: 'build'
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration)'

    # # This task was missing from your YAML but is needed for the deploy stage
    # - task: PublishBuildArtifacts@1
    #   displayName: 'Publish Artifact'
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'webapp'
    #     publishLocation: 'Container'