# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'pcso-dev'

# variables:
#   buildConfiguration: 'dev'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
# steps:
# - task: DotNetCoreCLI@2


variables:
  buildConfiguration: 'Release'
  # The path to the project file from the sample repo
  projectPath: 'pipelines-dotnet-core.csproj'

stages:
# Define the pipeline stages - Build stage is responsible for building and packaging the application
- stage: Build
  displayName: 'Build Stage'
  jobs:
  # A job represents a series of steps that run on the same agent
  - job: BuildJob
    pool:
      # Using the self-hosted agent pool named 'pcso-dev'
      name: 'pcso-dev'
    steps:
    # Explicitly checkout the repository code to the agent
    - checkout: self

    # Build the .NET Core project using the DotNetCoreCLI task
    - task: DotNetCoreCLI@2
      displayName: 'Build Project'
      inputs:
        command: 'build'             # Use the build command
        projects: '$(projectPath)'    # Project file to build (defined in variables)
        arguments: '--configuration $(buildConfiguration)'  # Build configuration (Release)

    # Publish the project to prepare it for deployment
    - task: DotNetCoreCLI@2
      displayName: 'Publish Project'
      inputs:
        command: 'publish'           # Use the publish command
        publishWebProjects: false    # Only publish specified projects, not all web projects
        projects: '$(projectPath)'    # Project file to publish
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'  # Output to staging directory
        zipAfterPublish: true        # Create a zip file after publishing

    # Publish the build artifacts so they can be used by the deployment stage
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path containing files to publish
        ArtifactName: 'webapp'                              # Name of the artifact to create
        publishLocation: 'Container'                        # Publish to pipeline artifact storage

- stage: Deploy
  displayName: 'Deploy to Dev Environment'
  dependsOn: Build
  jobs:
  - deployment: DeployToVM
    displayName: 'Deploy to EC2 Instance'
    environment:
      name: 'dev'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          # Use the modern and more reliable download task
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Artifact'
            inputs:
              buildType: 'current'
              artifactName: 'webapp'
              targetPath: '$(System.ArtifactsDirectory)'

          - task: PowerShell@2
            displayName: 'Deploy and Run Web App'
            inputs:
              targetType: 'inline'
              script: |
                # The download task places the zip file in a folder named after the artifact
                $sourceZip = '$(System.ArtifactsDirectory)/webapp/pipelines-dotnet-core.zip'
                $destination = '$(Agent.ToolsDirectory)/webapp'

                Write-Host "Unzipping from $sourceZip to $destination..."
                Expand-Archive -Path $sourceZip -DestinationPath $destination -Force
                
                Write-Host "Starting the application..."
                Start-Process -FilePath "dotnet" -ArgumentList "'$destination/pipelines-dotnet-core.dll'" -WindowStyle Hidden